import request from 'supertest';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import app from '../src/app';
import { getAIServices, resetAIServices } from '../src/services/ai/aiContainer';
import { GeminiLLMService } from '../src/services/ai/gemini/geminiLLMService';
import { GeminiEmbeddingService } from '../src/services/ai/gemini/geminiEmbeddingService';
import Level1Question, { ILevel1Question } from '../src/models/Level1Question';
import Answer, { IAnswer } from '../src/models/Answer';
import ConsultationQuery from '../src/models/ConsultationQuery';
import ChatbotSession from '../src/models/ChatbotSession';

describe('Chatbot Live Gemini & Atlas Integration Test Suite', () => {
  let mongoServer: MongoMemoryServer;
  const originalUseMockAi = process.env.USE_MOCK_AI;

  beforeAll(async () => {
    // Force live Gemini services for this suite
    process.env.USE_MOCK_AI = 'false';
    resetAIServices();

    mongoServer = await MongoMemoryServer.create();
    await mongoose.connect(mongoServer.getUri());
  }, 30000);

  afterAll(async () => {
    await mongoose.disconnect();
    await mongoServer.stop();
    process.env.USE_MOCK_AI = originalUseMockAi;
    resetAIServices();
  });

  afterEach(async () => {
    const collections = mongoose.connection.collections;
    for (const key in collections) {
      await collections[key].deleteMany({});
    }
  });

  it('R1: should default to real Gemini services (GeminiLLMService & GeminiEmbeddingService) when key is present', () => {
    const ai = getAIServices();
    expect(ai.llm).toBeInstanceOf(GeminiLLMService);
    expect(ai.embedding).toBeInstanceOf(GeminiEmbeddingService);
    expect(ai.embedding.dimensions).toBe(1536);
  });

  it('R2: should generate 1536-dimensional live embeddings via GeminiEmbeddingService', async () => {
    const ai = getAIServices();
    const embedding = await ai.embedding.generateEmbedding('tension headache relief');
    expect(Array.isArray(embedding)).toBe(true);
    expect(embedding.length).toBe(1536);
    expect(typeof embedding[0]).toBe('number');
  }, 30000);

  it('R3: should query /api/chatbot/query and return dynamic LLM generated answer without stubs', async () => {
    const ai = getAIServices();
    const questionText = 'What is the recommended homeopathic treatment for tension headaches?';
    const embedding = await ai.embedding.generateEmbedding(questionText);

    const question = (await Level1Question.create({
      canonicalQuestionText: questionText,
      embedding,
      tags: ['headache', 'tension'],
      isActive: true,
      version: 1,
    })) as ILevel1Question;

    const answer = (await Answer.create({
      level1QuestionId: question._id,
      answerText: 'Standard remedy guidance: Belladonna 30C or Nux Vomica 30C depending on acute throbbing nature.',
      dosageInstructions: 'Take 4 pills, 2 times daily dissolved under tongue.',
      homeRemedyText: 'Rest in a quiet, dark room and stay hydrated with warm fluids.',
      safetyDisclaimerText: 'If headache is accompanied by sudden neurological deficits, seek immediate emergency care.',
    })) as IAnswer;

    const res = await request(app)
      .post('/api/chatbot/query')
      .send({
        queryText: questionText,
        intent: 'direct_answer',
        language: 'en',
        inputMode: 'text',
      });

    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.matchConfident).toBe(true);
    expect(res.body.answer).toBeDefined();
    expect(res.body.answer.id).toBe(answer._id.toString());
    expect(res.body.answer.answerText).toBeDefined();

    const answerText = res.body.answer.answerText;
    expect(typeof answerText).toBe('string');
    expect(answerText.length).toBeGreaterThan(30);

    // Assert that the answer is dynamically generated by Gemini and not any hardcoded stub
    expect(answerText).not.toContain('Guidance for query: "');
    expect(answerText).not.toContain('Here is your personalized homeopathic healing regimen curated by Dr. Anjali Jariwala:');
    expect(answerText).not.toEqual('Standard remedy guidance: Belladonna 30C or Nux Vomica 30C depending on acute throbbing nature.');

    // Verify session logging
    const session = await ChatbotSession.findById(res.body.sessionId);
    expect(session).not.toBeNull();
    expect(session!.matchConfident).toBe(true);
  }, 45000);

  it('R4: should resolve consultation answer via /api/chatbot/consultation-answer with dynamic LLM personalization', async () => {
    const ai = getAIServices();
    const queryText = 'What homeopathic remedies help with acute migraine pain?';
    const embedding = await ai.embedding.generateEmbedding(queryText);

    const question = (await Level1Question.create({
      canonicalQuestionText: queryText,
      embedding,
      tags: ['migraine', 'headache'],
      isActive: true,
      version: 1,
    })) as ILevel1Question;

    const severeAnswer = (await Answer.create({
      level1QuestionId: question._id,
      answerText: 'Acute severe migraine remedy: Belladonna 200CK for violent throbbing pains aggravated by light and noise.',
      dosageInstructions: '4 pellets every 2 hours until symptom reduction.',
      safetyDisclaimerText: 'Consult your physician if severe head pain is sudden and explosive.',
    })) as IAnswer;

    await ConsultationQuery.create({
      level1QuestionId: question._id,
      diagnosticQuestions: [
        { id: 'q1', questionText: 'Is the headache throbbing or pulsating in nature?' },
        { id: 'q2', questionText: 'Is there associated nausea or severe sensitivity to light?' },
      ],
      answerBranches: [
        {
          conditions: { q1: 'yes', q2: 'yes' },
          resolvedAnswerId: severeAnswer._id,
        },
      ],
    });

    // 1. Trigger consultation query to initiate session
    const queryRes = await request(app)
      .post('/api/chatbot/query')
      .send({
        queryText,
        intent: 'consultation',
      });

    expect(queryRes.status).toBe(200);
    expect(queryRes.body.success).toBe(true);
    const sessionId = queryRes.body.sessionId;
    expect(sessionId).toBeDefined();

    // 2. Submit consultation answers
    const answerRes = await request(app)
      .post('/api/chatbot/consultation-answer')
      .send({
        sessionId,
        answers: { q1: 'yes', q2: 'yes' },
      });

    expect(answerRes.status).toBe(200);
    expect(answerRes.body.success).toBe(true);
    expect(answerRes.body.answer).toBeDefined();
    expect(answerRes.body.answer.id).toBe(severeAnswer._id.toString());
    expect(answerRes.body.answer.personalizedAnswer).toBeDefined();

    const personalized = answerRes.body.answer.personalizedAnswer;
    expect(personalized).toContain('Personalized Homeopathic Plan');
    // Ensure it contains dynamic content reflecting migraine/belladonna
    expect(personalized.toLowerCase()).toMatch(/migraine|belladonna|throbbing|plan/);
  }, 45000);
});
